export enum QUERYKEYS {
  FETCHPROFILE = "FETCHPROFILE",
  FETCHPROFILEPICTURE = "FETCHPROFILEPICTURE",
  FETCHTEAMS = "FETCHTEAMS",
  FETCHROLES = "FETCHROLES",
  FETCHPERMISSIONS = "FETCHPERMISSIONS",
  FETCHTEMPLATES = "FETCHTEMPLATES",
  FETCHSINGLETEMPLATE = "FETCHSINGLETEMPLATE",
  FETCHSINGLETEMPLATEFILE = "FETCHSINGLETEMPLATEFILE",
  FETCHCOLUMNMAPPING = "FETCHCOLUMNMAPPING",
  FETCHUSERS = "FETCHUSERS",

  FETCHREPORTS = "FETCHREPORTS",
  FETCHSINGLEREPORT = "FETCHSINGLEREPORT",
  FETCHGOOGLEURL = "FETCHGOOGLEURL"
}
