export enum QUERYKEYS {
  FETCHPROFILE = "FETCHPROFILE",
  FETCHPROFILEPICTURE = "FETCHPROFILEPICTURE",
  FETCHROLES = "FETCHROLES",
  FETCHPERMISSIONS = "FETCHPERMISSIONS",
  FETCHUSERS = "FETCHUSERS",
  FETCHAPPUSERS = "FETCHAPPUSERS",
  FETCHSYSTEMUSERS = "FETCHSYSTEMUSERS"
}
