export enum QUERYKEYS {
  FETCHPROFILE = "FETCHPROFILE",
  FETCHPROFILEPICTURE = "FETCHPROFILEPICTURE",
  FETCHROLES = "FETCHROLES",
  FETCHROLE = "FETCHROLE",
  FETCHPERMISSIONS = "FETCHPERMISSIONS",
  FETCHUSERS = "FETCHUSERS",
  FETCHAPPUSERS = "FETCHAPPUSERS",
  FETCHSYSTEMUSERS = "FETCHSYSTEMUSERS",
  DECISONS = "DECISONS",
  FETCHFACILITIES = "FETCHFACILITIES",
  FETCHSINGLEFACILITY = "FETCHSINGLEFACILITY",
  FETCHQUIZZES = "FETCHQUIZZES",
  FETCHQUIZQUESTIONS = "FETCHQUIZQUESTIONS"
}
